AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Infrastructure for Java App using secondary VPC resources'

Parameters:
  VPCStackName:
    Description: >
      Name of the secondary VPC/infrastructure stack.
    Type: String
    Default: TaskSphere-VPC

  TaskDefinition:
    Description: ARN of the existing ECS Task Definition
    Type: String

  ContainerPort:
    Description: Port the container exposes
    Type: Number
    Default: 5000

Resources:
  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AWS::StackName}-Cluster-Secondary"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-Cluster-Secondary"

  # Task Execution Role and Task Role
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  # CloudWatch Logs Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${AWS::StackName}-Secondary"
      RetentionInDays: 30

  # ECS Service using the existing Task Definition
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ALBListenerRule
    Properties:
      ServiceName: !Sub "${AWS::StackName}-Service-Secondary"
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentController:
        Type: CODE_DEPLOY
      DesiredCount: 2
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - Fn::ImportValue: !Sub "TaskSphere-VPC-ECSSecurityGroup-Secondary"
          Subnets:
            - Fn::ImportValue: !Sub "TaskSphere-VPC-PrivateSubnet1-Secondary"
            - Fn::ImportValue: !Sub "TaskSphere-VPC-PrivateSubnet2-Secondary"
      LoadBalancers:
        - ContainerName: tasksphere
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !ImportValue "TaskSphere-VPC-BlueTargetGroup-Secondary"
      HealthCheckGracePeriodSeconds: 60
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100

  # ALB Listener Rule
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !ImportValue "TaskSphere-VPC-BlueTargetGroup-Secondary"
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      ListenerArn: !ImportValue "TaskSphere-VPC-ProductionListener-Secondary"
      Priority: 1

  # Auto Scaling
  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Sub "service/${ECSCluster}/${ECSService.Name}"
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService"

  ScalingPolicyCPU:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-ScalingPolicy-CPU-Secondary"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 70
        ScaleInCooldown: 300
        ScaleOutCooldown: 300

  ScalingPolicyMemory:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-ScalingPolicy-Memory-Secondary"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        TargetValue: 70
        ScaleInCooldown: 300
        ScaleOutCooldown: 300

  # CodeDeploy Resources
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub "${AWS::StackName}-Application-Secondary"
      ComputePlatform: ECS

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: !Sub "${AWS::StackName}-DeploymentGroup-Secondary"
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      ServiceRoleArn: !GetAtt CodeDeployServiceRole.Arn
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      ECSServices:
        - ClusterName: !Ref ECSCluster
          ServiceName: !GetAtt ECSService.Name
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - ProdTrafficRoute:
              ListenerArns:
                - !ImportValue "TaskSphere-VPC-ProductionListener-Secondary"
            TargetGroups:
              - Name: !Select [1, !Split ["/", !ImportValue "TaskSphere-VPC-BlueTargetGroup-Secondary"]]
              - Name: !Select [1, !Split ["/", !ImportValue "TaskSphere-VPC-GreenTargetGroup-Secondary"]]

  # CodeDeploy Service Role
  CodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS

Outputs:
  ECSCluster:
    Description: ECS Cluster Name (Secondary)
    Value: !Ref ECSCluster
    Export:
      Name: !Sub "${AWS::StackName}-ECSCluster-Secondary"

  ECSService:
    Description: ECS Service Name (Secondary)
    Value: !GetAtt ECSService.Name
    Export:
      Name: !Sub "${AWS::StackName}-ECSService-Secondary"

  CodeDeployApplication:
    Description: CodeDeploy Application (Secondary)
    Value: !Ref CodeDeployApplication
    Export:
      Name: !Sub "${AWS::StackName}-CodeDeployApplication-Secondary"

  CodeDeployDeploymentGroup:
    Description: CodeDeploy Deployment Group (Secondary)
    Value: !Ref CodeDeployDeploymentGroup
    Export:
      Name: !Sub "${AWS::StackName}-CodeDeployDeploymentGroup-Secondary"